#!/usr/bin/env python
# Find epsilon boundary conditions

from subprocess import call
import os,sys
import numpy as np
import json

# Function to replace tpphi expression
def replace_tpphi(case,rp,ks,pk,rt,ph):
        tpphiFile = case+'/0/tpphi'

        f = open(tpphiFile,'r')
        filedata = f.read()
        f.close()

	tpphiExpression = str(ks)
	pkValue = str(pk)
	rtValue = str(rt)
	phValue = str(ph)
	
	if(rtValue == "fixedratio"):
		newdata = filedata.replace("<ksValueExpression>",tpphiExpression)
		newdata = newdata.replace("<pkCValue>",pkValue)
		newdata = newdata.replace("<rTypeValue>",rtValue)

	if(rtValue == "pow"):
		newdata = filedata.replace("<ksValueExpression>",tpphiExpression)
		newdata = newdata.replace("<pkCValue>",pkValue)
		newdata = newdata.replace("<rTypeValue>",rtValue)

	if(rtValue == "calcratio"):
		newdata = filedata.replace("<ksValueExpression>",tpphiExpression)
		newdata = newdata.replace("<pkCValue>",pkValue)
		newdata = newdata.replace("<rTypeValue>",rtValue)
		
	if(rtValue == "fixed"):
		newdata = filedata.replace("<ksValueExpression>",tpphiExpression)
		newdata = newdata.replace("<pkCValue>",phValue)
		newdata = newdata.replace("<rTypeValue>",rtValue)
		
        f = open(tpphiFile,'w')
        f.write(newdata)
        f.close()

# Function to replace k expression
def replace_k(case,rp,ks):
        kFile = case+'/0/k'

        f = open(kFile,'r')
        filedata = f.read()
        f.close()

	kExpression = str(ks)

        newdata = filedata.replace("<ksValueExpression>",kExpression)

        f = open(kFile,'w')
        f.write(newdata)
        f.close()
		
# Function to replace k expression
def replace_psi(case,rp,ks):
        psiFile = case+'/0/tppsi'

        f = open(psiFile,'r')
        filedata = f.read()
        f.close()

	kExpression = str(ks)

        newdata = filedata.replace("<ksValueExpression>",kExpression)

        f = open(psiFile,'w')
        f.write(newdata)
        f.close()
		
# Function to replace f expression
def replace_f(case,rp,ks):
        fFile = case+'/0/f'

        f = open(fFile,'r')
        filedata = f.read()
        f.close()

	fExpression = str(ks)

        newdata = filedata.replace("<ksValueExpression>",fExpression)

        f = open(fFile,'w')
        f.write(newdata)
        f.close()	
		
# Function to replace epsilon expression
def replace_eps(case,rp,ks):
        epsFile = case+'/0/epsilon'

        f = open(epsFile,'r')
        filedata = f.read()
        f.close()

	epsExpression = str(ks)

        newdata = filedata.replace("<ksValueExpression>",epsExpression)

        f = open(epsFile,'w')
        f.write(newdata)
        f.close()

# Source the foam-extend bashrc file
call(['/bin/bash','-i','-c','fe32'])

# Input arguments/data
jsonFile=sys.argv[1]

# Set up case dirs
runDir = os.environ.get('FOAM_RUN')
scriptDir = os.path.dirname(os.path.abspath(__file__))
caseRunnerDir = os.path.dirname(scriptDir)

# Load json data
json_data=open(caseRunnerDir+'/cases/'+jsonFile)
case = json.load(json_data)
json_data.close()

# Set up case runs
caseTemplate = case['template']
caseTemplatePath =  caseRunnerDir + '/' + caseTemplate
newCaseRoot = case['name']
newCasePath = runDir + '/' + newCaseRoot

submitFlag = case["submit"]
decomposeFlag = case["decompose"]
epsType = case["epsType"]
serialRun = case["serialRun"]
pkratio = case["pkC"]
rType = case["rType"]
ellipticCase = case["elliptic"]

constantE   = np.array(case["data"]["constantE"])
constantL   = np.array(case["data"]["constantL"])
lengthScale = np.array(case["data"]["lengthScale"])
phiValue    = np.array(case["data"]["phi"])
rPlus 	    = np.array(case["data"]["rplus"])
constantC   = np.array(case["data"]["constantC"])
ks		    = np.array(case["data"]["ks"])

nCases = rPlus.shape[0]
nCons  = constantC.shape[0]

# Copy and run loop
for n in range(1,nCases+1):
	newCase = newCasePath+'_'+str(rPlus[n-1])+'_'+str(phiValue[n-1])
	print 'Case: ' + newCase
	result = call('cp -R '+caseTemplatePath+'/ '+newCase,shell=True)

	if result == 0:
		replace_eps(newCase,rPlus[n-1],ks[n-1])
		replace_tpphi(newCase,rPlus[n-1],ks[n-1],pkratio,rType,phiValue[n-1])
		replace_k(newCase,rPlus[n-1],ks[n-1])
		replace_psi(newCase,rPlus[n-1],ks[n-1])
		if ellipticCase == "yes":
			replace_f(newCase,rPlus[n-1],ks[n-1])

		if decomposeFlag == 'yes':
			decompresult = call('cd '+newCase+' && decomposePar -force && cd ..',shell=True)

		if submitFlag == 'yes':
			if serialRun == "no":
				bsubresult = call('cd '+newCase+' && bsub < job.mpi && cd ..',shell=True)
			if serialRun == "yes":
				bsubresult = call('cd '+newCase+' && bsub < job.serial.intel.mpi && cd ..',shell=True)