#!/usr/bin/env python
# Find epsilon boundary conditions

from subprocess import call
import os,sys
import numpy as np
import json

# Source the foam-extend bashrc file
call(['/bin/bash','-i','-c','fe32'])

# Input arguments/data
jsonFile=sys.argv[1]

# Set up case dirs
runDir = os.environ.get('FOAM_RUN')
scriptDir = os.path.dirname(os.path.abspath(__file__))
caseRunnerDir = os.path.dirname(scriptDir)

# Load json data
json_data=open(caseRunnerDir+'/cases/'+jsonFile)
case = json.load(json_data)
json_data.close()

# Set up case runs
caseTemplate = case['template']
caseTemplatePath =  caseRunnerDir + '/' + caseTemplate
newCaseRoot = case['name']
newCasePath = runDir + '/' + newCaseRoot

submitFlag = case["submit"]
decomposeFlag = case["decompose"]
epsType = case["epsType"]
serialRun = case["serialRun"]

constant1   = np.array(case["data"]["constant1"])
constant2   = np.array(case["data"]["constant2"])
constant3   = np.array(case["data"]["constant3"])

n_c_one = constant1.shape[0]
n_c_two  = constant2.shape[0]
n_c_three = constant3.shape[0]

# Copy and run loop
for i in range(1,n_c_one+1):
	for c in range(1,n_c_two+1):
		for n in range(1,n_c_three+1):
			newCase = newCasePath+'_'+str(constant1[i-1])+'_'+str(constant2[c-1])+'_'+str(constant3[n-1])
			
			if(serialRun == "no"):
				# Reconstruct case
				recresult = call('cd '+newCase+' && reconstructPar && cd ..',shell=True)
			
				# Decompose case
				decresult = call('cd '+newCase+' && decomposePar -force && cd ..',shell=True)

				# Resubmit case
				bsubresult = call('cd '+newCase+' && bsub < job.mpi && cd ..',shell=True)
			
			if(serialRun == "yes"):
				# Resubmit case
				bsubresult = call('cd '+newCase+' && bsub < job.serial.mpi && cd ..',shell=True)