#!/usr/bin/env python
# Find epsilon boundary conditions

from subprocess import call
import os,sys
import numpy as np

# Source the foam-extend bashrc file
call(['/bin/bash','-i','-c','fe32'])

# Set up case dirs
runDir = os.environ.get('FOAM_RUN')
newCaseRoot = 'channel_3d_rough_epsTest_kuTau'
newCasePath = runDir + '/' + newCaseRoot

# Set up case runs
rPlus 	    = np.array([20, 45, 70, 100])
constantC   = np.array([0.01, 0.1, 1, 3])

nCases = rPlus.shape[0]
nCons  = constantC.shape[0]

# Copy and run loop
for c in range(1,nCons+1):
	for n in range(1,nCases+1):
        	newCase = newCasePath+'_'+str(rPlus[n-1])+'_'+str(constantC[c-1])
		
		# Reconstruct case
                recresult = call('cd '+newCase+' && reconstructPar && cd ..',shell=True)
		
		# Decompose case
		decresult = call('cd '+newCase+' && decomposePar -force && cd ..',shell=True)

		# Resubmit case
		bsubresult = call('cd '+newCase+' && bsub < job.mpi && cd ..',shell=True)
